// This file is computer-generated by onnx2c 
// Command Line: onnx2c -f moons_entry moons.onnx

// onnx2c
// Git Branch: master
// Git Commit: a037acc

// ONNX Model
// Produced By: pytorch, version 2.14.0
// ONNX IR version: 13

#include <float.h>
#include <math.h>
#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include <stdlib.h>

#define MAX(X,Y) ( X > Y ? X : Y)
#define MIN(X,Y) ( X < Y ? X : Y)
#define CLIP(X,L) ( MAX(MIN(X,L), -L) )

#if __STDC_VERSION__ < 199901L
#define FUNC_PREFIX
#else
#define FUNC_PREFIX static inline
#endif

static const float tensor_fc1_weight[8][2] = 
{
  {-0.13078217208385467529f, 1.05847036838531494141f},
  {-2.65796113014221191406f, 0.56889921426773071289f},
  {-0.27234524488449096680f, 0.18961589038372039795f},
  {1.16637003421783447266f, 0.88369089365005493164f},
  {0.04846294596791267395f, 0.69351869821548461914f},
  {0.69948333501815795898f, -0.89389556646347045898f},
  {-1.97665143013000488281f, 0.88164484500885009766f},
  {-0.26763355731964111328f, 0.86485463380813598633f}
};
static const float tensor_fc1_bias[8] = 
{0.81357538700103759766f, -1.03621780872344970703f, -0.47937673330307006836f, 0.20440295338630676270f, 0.42001643776893615723f, 1.56905579566955566406f, -0.98824965953826904297f, 0.92078316211700439453f};
static const float tensor_fc2_weight[2][8] = 
{
  {0.58478248119354248047f, 2.21917605400085449219f, 0.32013419270515441895f, 0.40729612112045288086f, 0.22923342883586883545f, -0.89168697595596313477f, 1.47779440879821777344f, 0.77015370130538940430f},
  {-0.87093538045883178711f, -2.34451818466186523438f, -0.24700669944286346436f, -1.06640148162841796875f, -0.65819251537322998047f, 1.10609400272369384766f, -1.45784616470336914062f, -0.29332563281059265137f}
};
static const float tensor_fc2_bias[2] = 
{-1.01118826866149902344f, 0.84852278232574462891f};
union tensor_union_0 {
float tensor__fc1_Gemm_output_0[1][8];
};
static union tensor_union_0 tu0;

union tensor_union_1 {
float tensor__relu_Relu_output_0[1][8];
};
static union tensor_union_1 tu1;


/*
 * Operand:           Gemm
 * Name in ONNX file: /fc1/Gemm
 */
FUNC_PREFIX void node__fc1_Gemm( const float A[1][2], const float B[8][2], const float C[8], float Y[1][8] )
{
	/* Gemm */
	/* alpha   = 1.00000000000000000000
	   beta    = 1.00000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 2;
	const int N = 8;
	float alpha = 1.00000000000000000000;
	float beta = 1.00000000000000000000;
	float (*C_)[8]  = (float(*)[8])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][c] * beta;
			Y[r][c] = tmp;
	}
}

/*
 * Operand:           Relu
 * Name in ONNX file: /relu/Relu
 */
FUNC_PREFIX void node__relu_Relu( const float X[1][8], float Y[1][8] )
{
	/*Relu*/
	float *X_ptr = (float*)X;
	float *Y_ptr = (float*)Y;
	uint32_t i;
	for( i=0; i<8; i++ )
		Y_ptr[i] = X_ptr[i] > 0 ? X_ptr[i] : 0;

}

/*
 * Operand:           Gemm
 * Name in ONNX file: /fc2/Gemm
 */
FUNC_PREFIX void node__fc2_Gemm( const float A[1][8], const float B[2][8], const float C[2], float Y[1][2] )
{
	/* Gemm */
	/* alpha   = 1.00000000000000000000
	   beta    = 1.00000000000000000000
	   transA  = 0
	   transB  = 1
	 */
	const int M = 1;
	const int K = 8;
	const int N = 2;
	float alpha = 1.00000000000000000000;
	float beta = 1.00000000000000000000;
	float (*C_)[2]  = (float(*)[2])C;
	for( uint32_t r=0; r<M; r++ )
		for( uint32_t c=0; c<N; c++ ) {
			float ABrc = 0;
			for( uint32_t i=0; i<K; i++ ) {
				float B_el = B[c][i];
				ABrc += A[r][i] * B_el;
			}
			float tmp = ABrc * alpha;
			tmp += C_[0][c] * beta;
			Y[r][c] = tmp;
	}
}


void moons_entry(const float tensor_input[1][2], float tensor_output[1][2]){
	node__fc1_Gemm( tensor_input, tensor_fc1_weight, tensor_fc1_bias, tu0.tensor__fc1_Gemm_output_0);
	node__relu_Relu( tu0.tensor__fc1_Gemm_output_0, tu1.tensor__relu_Relu_output_0);
	node__fc2_Gemm( tu1.tensor__relu_Relu_output_0, tensor_fc2_weight, tensor_fc2_bias, tensor_output);
}
