/*
    Copyright 2019 Joel Svensson	svenssonjoel@yahoo.se

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/* The codes are autogenerated using python script in utils directory */ 

//Total number of bits 392

char *codes[65][2] =
  {{ "lambda", "110001" },
   { "z", "001101" },
   { "x", "000000" },
   { "y", "001110" },
   { "v", "001011" },
   { "w", "000001" },
   { "t", "010100" },
   { "u", "000110" },
   { "r", "010000" },
   { "s", "010101" },
   { "p", "1111111" },
   { "q", "010001" },
   { "n", "001100" },
   { "o", "000100" },
   { "l", "001111" },
   { "m", "001000" },
   { "j", "000111" },
   { "k", "010010" },
   { "h", "1111110" },
   { "i", "010110" },
   { "f", "001001" },
   { "g", "000101" },
   { "d", "010111" },
   { "e", "010011" },
   { "b", "001010" },
   { "c", "000010" },
   { "car", "101100" },
   { "a", "000011" },
   { "8", "011001" },
   { "let", "100010" },
   { "((", "101001" },
   { ">", "111101" },
   { "\\", "110101" },
   { "quote", "110000" },
   { "nil", "101010" },
   { "closure", "100100" },
   { "define", "100011" },
   { "<", "110100" },
   { "=", "111000" },
   { "5", "011100" },
   { "9", "011011" },
   { "6", "011111" },
   { "7", "011110" },
   { "4", "011101" },
   { "\"", "110110" },
   { "2", "100001" },
   { "3", "100000" },
   { "0", "011010" },
   { "))))", "100110" },
   { ".", "111100" },
   { "/", "111110" },
   { "-", "111010" },
   { "*", "111001" },
   { "+", "111011" },
   { "(", "101110" },
   { ")", "101000" },
   { "'", "101011" },
   { "#", "110111" },
   { "1", "011000" },
   { "if", "100111" },
   { ")))", "110010" },
   { "cdr", "101111" },
   { "))", "110011" },
   { "list", "100101" },
   { "cons", "101101" }};
