/*
    Copyright 2019 Joel Svensson	svenssonjoel@yahoo.se

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/* The codes are autogenerated using python script in utils directory */ 

//Total number of bits 388
char *codes[63][2] =
  {{ "lambda", "101100" },
   { "z", "010110" },
   { "x", "001011" },
   { "y", "010111" },
   { "v", "001000" },
   { "w", "001110" },
   { "t", "010011" },
   { "u", "001001" },
   { "r", "010001" },
   { "s", "011000" },
   { "p", "011010" },
   { "q", "010100" },
   { "n", "000101" },
   { "o", "000001" },
   { "l", "001010" },
   { "m", "000111" },
   { "j", "010010" },
   { "k", "001111" },
   { "h", "010101" },
   { "i", "011001" },
   { "f", "001100" },
   { "g", "000110" },
   { "d", "010000" },
   { "e", "000010" },
   { "b", "000011" },
   { "c", "000100" },
   { "car", "100111" },
   { "a", "001101" },
   { "let", "100011" },
   { "((", "100100" },
   { ">", "11101" },
   { "quote", "011101" },
   { "nil", "101010" },
   { "closure", "011111" },
   { "define", "011110" },
   { "<", "11110" },
   { "=", "11000" },
   { "8", "01101101" },
   { "9", "01101100" },
   { "6", "01101111" },
   { "7", "01101110" },
   { "4", "01110001" },
   { "5", "01110000" },
   { "2", "01110011" },
   { "3", "01110010" },
   { "0", "0000001" },
   { "))))", "101011" },
   { ".", "11010" },
   { "/", "11111" },
   { "-", "11011" },
   { "*", "11001" },
   { "+", "11100" },
   { "(", "100101" },
   { ")", "101110" },
   { "'", "101101" },
   { "1", "0000000" },
   { "if", "100001" },
   { ")))", "101000" },
   { "cdr", "100110" },
   { "))", "101001" },
   { "TOGGLE_COMPRESS", "101111" },
   { "list", "100000" },
   { "cons", "100010" }};
