/*
    Copyright 2019 Joel Svensson	svenssonjoel@yahoo.se

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/


/* The codes are autogenerated using python script in utils directory */ 

//Total number of bits 392
char *codes[65][2] =
  {{ "lambda", "001010" },
   { "z", "010000" },
   { "x", "010111" },
   { "y", "010001" },
   { "v", "010010" },
   { "w", "011010" },
   { "t", "100000" },
   { "u", "010011" },
   { "r", "100101" },
   { "s", "100010" },
   { "p", "101000" },
   { "q", "010100" },
   { "n", "011110" },
   { "o", "001111" },
   { "l", "010110" },
   { "m", "011100" },
   { "j", "011001" },
   { "k", "011011" },
   { "h", "010101" },
   { "i", "100100" },
   { "f", "011101" },
   { "g", "100111" },
   { "d", "100011" },
   { "e", "011000" },
   { "b", "100001" },
   { "c", "100110" },
   { "car", "000111" },
   { "a", "011111" },
   { "8", "101010" },
   { "let", "1111111" },
   { "((", "001100" },
   { ">", "110110" },
   { "\\", "111100" },
   { "quote", "001001" },
   { "nil", "001011" },
   { "closure", "001000" },
   { "define", "001110" },
   { "<", "110111" },
   { "=", "111110" },
   { "5", "101100" },
   { "9", "110010" },
   { "6", "110000" },
   { "7", "101001" },
   { "4", "110001" },
   { "\"", "111000" },
   { "2", "101011" },
   { "3", "101101" },
   { "0", "101110" },
   { "))))", "000000" },
   { ".", "111001" },
   { "/", "111010" },
   { "-", "110100" },
   { "*", "111011" },
   { "+", "110101" },
   { "(", "001101" },
   { ")", "000011" },
   { "'", "110011" },
   { "#", "111101" },
   { "1", "101111" },
   { "if", "000101" },
   { ")))", "000001" },
   { "cdr", "000110" },
   { "))", "000010" },
   { "list", "000100" },
   { "cons", "1111110" }};
